apiVersion: v1                  # API version for the PersistentVolumeClaim
kind: PersistentVolumeClaim     # Type of resource
metadata:
  name: my-pvc                   # Name of the PersistentVolumeClaim
  labels:
    app: my-application          # Optional: Labels to organize and select this PVC
spec:
  accessModes:
    - ReadWriteOnce              # Access mode (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  volumeMode: Filesystem         # Volume mode (Filesystem or Block)
  resources:
    requests:
      storage: 10Gi              # Requested storage size
  storageClassName: "standard"   # StorageClass name. Use "" for default StorageClass or specify.
  selector:
    matchLabels:
      type: local                # Optional: Selector to bind to specific PVs
  # Optional: Specific volumeName to bind
  # volumeName: "my-pv"
