apiVersion: v1               # API version for the PersistentVolume
kind: PersistentVolume       # Type of resource
metadata:
  name: my-pv                 # Name of the PersistentVolume
  labels:
    type: local               # Optional: Labels to organize and select this PV
spec:
  capacity:
    storage: 10Gi            # Size of the PersistentVolume
  accessModes:
    - ReadWriteOnce          # Access mode (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Reclaim policy (Retain, Delete, Recycle)
  storageClassName: "standard"           # StorageClass associated with this PV
  mountOptions:
    - hard
    - nfsvers=4.1            # Optional: Mount options for NFS
  hostPath:                  # Type of storage used (hostPath, nfs, etc.)
    path: "/mnt/data"        # Path on the host where the storage is located
    type: DirectoryOrCreate  # Will create the directory if it doesn't exist
  # For NFS, use:
  # nfs:
  #   path: /path/to/nfs
  #   server: nfs-server-ip
